// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RPCInput.proto

package adapter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPCInput struct {
	ServerName           string           `protobuf:"bytes,1,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	Func                 string           `protobuf:"bytes,2,opt,name=Func,proto3" json:"Func,omitempty"`
	Req                  []byte           `protobuf:"bytes,3,opt,name=Req,proto3" json:"Req,omitempty"`
	Opt                  map[int32]string `protobuf:"bytes,4,rep,name=Opt,proto3" json:"Opt,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RPCInput) Reset()         { *m = RPCInput{} }
func (m *RPCInput) String() string { return proto.CompactTextString(m) }
func (*RPCInput) ProtoMessage()    {}
func (*RPCInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d5bea30f7b246ca, []int{0}
}

func (m *RPCInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCInput.Unmarshal(m, b)
}
func (m *RPCInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCInput.Marshal(b, m, deterministic)
}
func (m *RPCInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCInput.Merge(m, src)
}
func (m *RPCInput) XXX_Size() int {
	return xxx_messageInfo_RPCInput.Size(m)
}
func (m *RPCInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCInput.DiscardUnknown(m)
}

var xxx_messageInfo_RPCInput proto.InternalMessageInfo

func (m *RPCInput) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *RPCInput) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func (m *RPCInput) GetReq() []byte {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *RPCInput) GetOpt() map[int32]string {
	if m != nil {
		return m.Opt
	}
	return nil
}

func init() {
	proto.RegisterType((*RPCInput)(nil), "adapter.RPCInput")
	proto.RegisterMapType((map[int32]string)(nil), "adapter.RPCInput.OptEntry")
}

func init() { proto.RegisterFile("RPCInput.proto", fileDescriptor_5d5bea30f7b246ca) }

var fileDescriptor_5d5bea30f7b246ca = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x0a, 0x70, 0xf6,
	0xcc, 0x2b, 0x28, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x4c, 0x49, 0x2c,
	0x28, 0x49, 0x2d, 0x52, 0xda, 0xc6, 0xc8, 0xc5, 0x01, 0x93, 0x13, 0x92, 0xe3, 0xe2, 0x0a, 0x4e,
	0x2d, 0x2a, 0x4b, 0x2d, 0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42,
	0x12, 0x11, 0x12, 0xe2, 0x62, 0x71, 0x2b, 0xcd, 0x4b, 0x96, 0x60, 0x02, 0xcb, 0x80, 0xd9, 0x42,
	0x02, 0x5c, 0xcc, 0x41, 0xa9, 0x85, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x20, 0xa6, 0x90,
	0x0e, 0x17, 0xb3, 0x7f, 0x41, 0x89, 0x04, 0x8b, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x94, 0x1e, 0xd4,
	0x26, 0x3d, 0xb8, 0x0b, 0xfc, 0x0b, 0x4a, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0x83, 0x40, 0xca, 0xa4,
	0xcc, 0xb8, 0x38, 0x60, 0x02, 0x20, 0xb3, 0xb2, 0x53, 0x2b, 0xc1, 0x16, 0xb3, 0x06, 0x81, 0x98,
	0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x50, 0x2b, 0x21, 0x1c, 0x2b, 0x26, 0x0b,
	0x46, 0x27, 0xce, 0x28, 0x98, 0x1f, 0x92, 0xd8, 0xc0, 0x7e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xa5, 0x3f, 0xca, 0xc3, 0xe5, 0x00, 0x00, 0x00,
}
