// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RPCOutput.proto

package adapter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPCOutput struct {
	Ret                  int32            `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Rsp                  []byte           `protobuf:"bytes,2,opt,name=Rsp,proto3" json:"Rsp,omitempty"`
	Opt                  map[int32]string `protobuf:"bytes,3,rep,name=Opt,proto3" json:"Opt,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Desc                 string           `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	ServerName           string           `protobuf:"bytes,5,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	Func                 string           `protobuf:"bytes,6,opt,name=Func,proto3" json:"Func,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RPCOutput) Reset()         { *m = RPCOutput{} }
func (m *RPCOutput) String() string { return proto.CompactTextString(m) }
func (*RPCOutput) ProtoMessage()    {}
func (*RPCOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_127107d20c6a154d, []int{0}
}

func (m *RPCOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCOutput.Unmarshal(m, b)
}
func (m *RPCOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCOutput.Marshal(b, m, deterministic)
}
func (m *RPCOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCOutput.Merge(m, src)
}
func (m *RPCOutput) XXX_Size() int {
	return xxx_messageInfo_RPCOutput.Size(m)
}
func (m *RPCOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCOutput.DiscardUnknown(m)
}

var xxx_messageInfo_RPCOutput proto.InternalMessageInfo

func (m *RPCOutput) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *RPCOutput) GetRsp() []byte {
	if m != nil {
		return m.Rsp
	}
	return nil
}

func (m *RPCOutput) GetOpt() map[int32]string {
	if m != nil {
		return m.Opt
	}
	return nil
}

func (m *RPCOutput) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RPCOutput) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *RPCOutput) GetFunc() string {
	if m != nil {
		return m.Func
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCOutput)(nil), "adapter.RPCOutput")
	proto.RegisterMapType((map[int32]string)(nil), "adapter.RPCOutput.OptEntry")
}

func init() { proto.RegisterFile("RPCOutput.proto", fileDescriptor_127107d20c6a154d) }

var fileDescriptor_127107d20c6a154d = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x4b, 0xc0, 0x30,
	0x10, 0xc5, 0x49, 0xd3, 0x56, 0x73, 0x0a, 0x4a, 0x70, 0x08, 0x0a, 0x12, 0x9c, 0xb2, 0xd8, 0x41,
	0x41, 0xc4, 0xd1, 0x7f, 0xa3, 0x95, 0xb8, 0xb9, 0xc5, 0x7a, 0x53, 0xb5, 0x0d, 0xe9, 0xa5, 0xd0,
	0x2f, 0xeb, 0x67, 0x91, 0xa4, 0x56, 0xdd, 0x7e, 0xb9, 0xcb, 0x7b, 0xf7, 0x1e, 0x1c, 0xd8, 0xe7,
	0xbb, 0x36, 0x92, 0x8f, 0xd4, 0xf8, 0x30, 0xd2, 0x28, 0x77, 0xdc, 0xbb, 0xf3, 0x84, 0xe1, 0xec,
	0x8b, 0x81, 0xf8, 0x5d, 0xca, 0x43, 0xe0, 0x16, 0x49, 0x31, 0xcd, 0x4c, 0x65, 0x13, 0xe6, 0xc9,
	0xe4, 0x55, 0xa1, 0x99, 0xd9, 0xb7, 0x09, 0xe5, 0x39, 0xf0, 0xd6, 0x93, 0xe2, 0x9a, 0x9b, 0xbd,
	0x8b, 0x93, 0xe6, 0xc7, 0xa8, 0xf9, 0xbb, 0xd0, 0x7a, 0x7a, 0x18, 0x28, 0x2c, 0x36, 0xfd, 0x93,
	0x12, 0xca, 0x7b, 0x9c, 0x3a, 0x55, 0x6a, 0x66, 0x84, 0xcd, 0x2c, 0x4f, 0x01, 0x5e, 0x30, 0xcc,
	0x18, 0x9e, 0xdc, 0x27, 0xaa, 0x2a, 0x6f, 0xfe, 0x4d, 0x92, 0xe6, 0x31, 0x0e, 0x9d, 0xaa, 0x57,
	0x4d, 0xe2, 0xe3, 0x2b, 0xd8, 0xdd, 0x8c, 0x53, 0xa8, 0x1e, 0x97, 0x2d, 0x66, 0x8f, 0x8b, 0x3c,
	0x82, 0x6a, 0x76, 0x1f, 0x11, 0x73, 0x50, 0x61, 0xd7, 0xc7, 0x4d, 0x71, 0xcd, 0x6e, 0xc5, 0xeb,
	0xd6, 0xf5, 0xad, 0xce, 0xdd, 0x2f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xad, 0x51, 0x6a, 0x36,
	0x0e, 0x01, 0x00, 0x00,
}
