settings:
  server:
    profile: pro # 环境配置

  network:
    protocol: udp # 协议
    ip: 10.10.30.232 # 网卡
    port: 8401 # 端口
    multicore: true # 是否多核处理
    requestURI: /sub # ws协议请求路径

  logger:
    path: ./logs/ # 日志保存路径
    level: debug # 日志级别

