// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

// protoc -I=. --go_out=. user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	HeadImg              string   `protobuf:"bytes,4,opt,name=head_img,json=headImg,proto3" json:"head_img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

type Friends struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	List                 []*User  `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Friends) Reset()         { *m = Friends{} }
func (m *Friends) String() string { return proto.CompactTextString(m) }
func (*Friends) ProtoMessage()    {}
func (*Friends) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Friends) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Friends.Unmarshal(m, b)
}
func (m *Friends) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Friends.Marshal(b, m, deterministic)
}
func (m *Friends) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Friends.Merge(m, src)
}
func (m *Friends) XXX_Size() int {
	return xxx_messageInfo_Friends.Size(m)
}
func (m *Friends) XXX_DiscardUnknown() {
	xxx_messageInfo_Friends.DiscardUnknown(m)
}

var xxx_messageInfo_Friends proto.InternalMessageInfo

func (m *Friends) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Friends) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Friends) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

type UserInfoRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type UserInfoResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserListRequest struct {
	Find *User `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	// 分页相关
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetFind() *User {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *UserListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserListRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UserListResponse struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List                 []*User  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserListResponse) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type FriendsListRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendsListRequest) Reset()         { *m = FriendsListRequest{} }
func (m *FriendsListRequest) String() string { return proto.CompactTextString(m) }
func (*FriendsListRequest) ProtoMessage()    {}
func (*FriendsListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *FriendsListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendsListRequest.Unmarshal(m, b)
}
func (m *FriendsListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendsListRequest.Marshal(b, m, deterministic)
}
func (m *FriendsListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendsListRequest.Merge(m, src)
}
func (m *FriendsListRequest) XXX_Size() int {
	return xxx_messageInfo_FriendsListRequest.Size(m)
}
func (m *FriendsListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendsListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FriendsListRequest proto.InternalMessageInfo

func (m *FriendsListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FriendsListResponse struct {
	Code                 int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	List                 []*Friends `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FriendsListResponse) Reset()         { *m = FriendsListResponse{} }
func (m *FriendsListResponse) String() string { return proto.CompactTextString(m) }
func (*FriendsListResponse) ProtoMessage()    {}
func (*FriendsListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *FriendsListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendsListResponse.Unmarshal(m, b)
}
func (m *FriendsListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendsListResponse.Marshal(b, m, deterministic)
}
func (m *FriendsListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendsListResponse.Merge(m, src)
}
func (m *FriendsListResponse) XXX_Size() int {
	return xxx_messageInfo_FriendsListResponse.Size(m)
}
func (m *FriendsListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendsListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FriendsListResponse proto.InternalMessageInfo

func (m *FriendsListResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FriendsListResponse) GetList() []*Friends {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Friends)(nil), "user.Friends")
	proto.RegisterType((*UserInfoRequest)(nil), "user.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "user.UserInfoResponse")
	proto.RegisterType((*UserListRequest)(nil), "user.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "user.UserListResponse")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*FriendsListRequest)(nil), "user.FriendsListRequest")
	proto.RegisterType((*FriendsListResponse)(nil), "user.FriendsListResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xea, 0x40,
	0x14, 0x4d, 0x3f, 0xa0, 0x7d, 0xf7, 0xbd, 0x3e, 0xc9, 0x68, 0x62, 0x61, 0x41, 0xb0, 0x6e, 0xd8,
	0xc8, 0x42, 0xff, 0x03, 0xb1, 0x09, 0xab, 0x89, 0x2e, 0x58, 0x91, 0xca, 0x0c, 0x75, 0x02, 0xcc,
	0xd4, 0x4e, 0x1b, 0x13, 0x7f, 0xbd, 0x99, 0x3b, 0x6d, 0x05, 0x8c, 0xb8, 0xbb, 0xe7, 0x7e, 0x9d,
	0x33, 0xe7, 0x0e, 0x40, 0xad, 0x79, 0x39, 0x2b, 0x4a, 0x55, 0x29, 0xe2, 0x9b, 0x38, 0x11, 0xe0,
	0x3f, 0x6b, 0x5e, 0x92, 0xff, 0xe0, 0x0a, 0x16, 0x3b, 0x13, 0x67, 0xea, 0x51, 0x57, 0x30, 0x32,
	0x82, 0x50, 0x8a, 0xf5, 0x56, 0x66, 0x7b, 0x1e, 0xbb, 0x13, 0x67, 0xfa, 0x87, 0x76, 0xd8, 0xd4,
	0xcc, 0x2c, 0xd6, 0x3c, 0x5b, 0x6b, 0x31, 0x19, 0x42, 0xf8, 0xca, 0x33, 0xb6, 0x12, 0xfb, 0x3c,
	0xf6, 0xb1, 0x16, 0x18, 0x9c, 0xee, 0xf3, 0xe4, 0x09, 0x82, 0x79, 0x29, 0xb8, 0x64, 0xfa, 0x1b,
	0xdb, 0x10, 0xc2, 0xbc, 0x54, 0x75, 0xb1, 0x12, 0x0c, 0xd9, 0x3c, 0x1a, 0x20, 0x4e, 0x19, 0x19,
	0x83, 0xbf, 0x13, 0xba, 0x8a, 0xbd, 0x89, 0x37, 0xfd, 0x7b, 0x0f, 0x33, 0x7c, 0x81, 0x91, 0x4c,
	0x31, 0x9f, 0xdc, 0xc2, 0x85, 0x41, 0xa9, 0xdc, 0x28, 0xca, 0xdf, 0x6a, 0xae, 0x2b, 0x32, 0x00,
	0xaf, 0xee, 0xd6, 0x9b, 0x30, 0x99, 0xc3, 0xe0, 0xab, 0x49, 0x17, 0x4a, 0x6a, 0x4e, 0x08, 0xf8,
	0x6b, 0xc5, 0x38, 0xb6, 0xf5, 0x28, 0xc6, 0x86, 0xcc, 0xec, 0xc7, 0x57, 0x9d, 0x90, 0xa1, 0x5b,
	0x4b, 0x4b, 0xb6, 0x10, 0xba, 0x6a, 0xc9, 0xc6, 0xe0, 0x6f, 0x84, 0xb4, 0x6c, 0x27, 0x23, 0x26,
	0x6f, 0x68, 0x8a, 0x2c, 0xb7, 0x26, 0x46, 0x14, 0x63, 0x93, 0xd3, 0xe2, 0xc3, 0x9a, 0x17, 0x51,
	0x8c, 0x93, 0x47, 0x2b, 0xd1, 0xae, 0x6e, 0x24, 0x5e, 0x41, 0xaf, 0x52, 0x55, 0xb6, 0xc3, 0xe5,
	0x11, 0xb5, 0xa0, 0x73, 0xc4, 0xfd, 0xc1, 0x91, 0x39, 0xfc, 0x5b, 0xa8, 0x5c, 0xc8, 0x56, 0xe1,
	0xe1, 0xb9, 0x9c, 0x93, 0x73, 0x8d, 0x20, 0x2c, 0x32, 0xad, 0xdf, 0x55, 0xc9, 0xda, 0x33, 0xb7,
	0x38, 0x59, 0x42, 0xd4, 0xec, 0x39, 0xe3, 0x18, 0x4a, 0xdc, 0x72, 0xd9, 0x4c, 0x5b, 0xf0, 0xab,
	0x8f, 0x77, 0x40, 0x9a, 0xaf, 0x70, 0x68, 0xe5, 0x35, 0x04, 0xa6, 0xba, 0xea, 0x6e, 0xd7, 0x37,
	0x30, 0x65, 0xc9, 0x02, 0x2e, 0x8f, 0xda, 0xcf, 0xe8, 0xb9, 0x39, 0x32, 0x27, 0xb2, 0xcc, 0xcd,
	0xb0, 0xf5, 0xe7, 0xa5, 0x8f, 0xff, 0xff, 0xe1, 0x33, 0x00, 0x00, 0xff, 0xff, 0xba, 0xec, 0xe6,
	0x94, 0x0d, 0x03, 0x00, 0x00,
}
