// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

// protoc -I=. --go_out=. user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	HeadImg              string   `protobuf:"bytes,4,opt,name=head_img,json=headImg,proto3" json:"head_img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetHeadImg() string {
	if m != nil {
		return m.HeadImg
	}
	return ""
}

type UserListRequest struct {
	// 分页相关
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListRequest) Reset()         { *m = UserListRequest{} }
func (m *UserListRequest) String() string { return proto.CompactTextString(m) }
func (*UserListRequest) ProtoMessage()    {}
func (*UserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListRequest.Unmarshal(m, b)
}
func (m *UserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListRequest.Marshal(b, m, deterministic)
}
func (m *UserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListRequest.Merge(m, src)
}
func (m *UserListRequest) XXX_Size() int {
	return xxx_messageInfo_UserListRequest.Size(m)
}
func (m *UserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserListRequest proto.InternalMessageInfo

func (m *UserListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *UserListRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type UserListResponse struct {
	Total                uint32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List                 []*User  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserListResponse) Reset()         { *m = UserListResponse{} }
func (m *UserListResponse) String() string { return proto.CompactTextString(m) }
func (*UserListResponse) ProtoMessage()    {}
func (*UserListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserListResponse.Unmarshal(m, b)
}
func (m *UserListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserListResponse.Marshal(b, m, deterministic)
}
func (m *UserListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserListResponse.Merge(m, src)
}
func (m *UserListResponse) XXX_Size() int {
	return xxx_messageInfo_UserListResponse.Size(m)
}
func (m *UserListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserListResponse proto.InternalMessageInfo

func (m *UserListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserListResponse) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*UserListRequest)(nil), "user.UserListRequest")
	proto.RegisterType((*UserListResponse)(nil), "user.UserListResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xb1, 0x4a, 0xc5, 0x40,
	0x10, 0x45, 0xc9, 0x66, 0xd5, 0xe7, 0xc8, 0x53, 0x19, 0x2c, 0x56, 0x0b, 0x09, 0xa9, 0x52, 0xa5,
	0xd0, 0xca, 0x3f, 0x50, 0xb0, 0x5a, 0xb0, 0x96, 0xd5, 0x0c, 0x71, 0x30, 0xc9, 0xc6, 0xcc, 0xa6,
	0xf1, 0xeb, 0x65, 0x27, 0xea, 0xeb, 0xee, 0x9d, 0xc3, 0xe1, 0x32, 0x00, 0xab, 0xd0, 0xd2, 0xce,
	0x4b, 0x4c, 0x11, 0x6d, 0xce, 0x35, 0x83, 0x7d, 0x11, 0x5a, 0xf0, 0x1c, 0x0c, 0x77, 0xae, 0xa8,
	0x8a, 0xa6, 0xf4, 0x86, 0x3b, 0xbc, 0x81, 0xdd, 0xc4, 0xef, 0x9f, 0x53, 0x18, 0xc9, 0x99, 0xaa,
	0x68, 0x4e, 0xfd, 0x7f, 0xcf, 0x2c, 0xbb, 0xca, 0xca, 0x8d, 0xfd, 0x75, 0xbc, 0x86, 0xdd, 0x07,
	0x85, 0xee, 0x95, 0xc7, 0xde, 0x59, 0x65, 0x27, 0xb9, 0x3f, 0x8d, 0x7d, 0xfd, 0x00, 0x17, 0x79,
	0xea, 0x99, 0x25, 0x79, 0xfa, 0x5a, 0x49, 0x12, 0x22, 0xd8, 0x39, 0xf4, 0xa4, 0xbb, 0x7b, 0xaf,
	0x39, 0xdf, 0x84, 0xbf, 0xb7, 0xd5, 0xbd, 0xd7, 0x5c, 0x3f, 0xc2, 0xe5, 0x41, 0x95, 0x39, 0x4e,
	0x42, 0x78, 0x05, 0x47, 0x29, 0xa6, 0x30, 0xfc, 0xca, 0x5b, 0xc1, 0x5b, 0xb0, 0x03, 0x4b, 0x72,
	0xa6, 0x2a, 0x9b, 0xb3, 0x3b, 0x68, 0xf5, 0xe1, 0xec, 0x7a, 0xbd, 0xbf, 0x1d, 0xeb, 0xf3, 0xf7,
	0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0xed, 0x06, 0x57, 0x0a, 0x01, 0x00, 0x00,
}
