// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

// protoc -I route route/route.proto --go_out=plugins=grpc:route

package route

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAddrListReq struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddrListReq) Reset()         { *m = GetAddrListReq{} }
func (m *GetAddrListReq) String() string { return proto.CompactTextString(m) }
func (*GetAddrListReq) ProtoMessage()    {}
func (*GetAddrListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{0}
}

func (m *GetAddrListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddrListReq.Unmarshal(m, b)
}
func (m *GetAddrListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddrListReq.Marshal(b, m, deterministic)
}
func (m *GetAddrListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddrListReq.Merge(m, src)
}
func (m *GetAddrListReq) XXX_Size() int {
	return xxx_messageInfo_GetAddrListReq.Size(m)
}
func (m *GetAddrListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddrListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddrListReq proto.InternalMessageInfo

func (m *GetAddrListReq) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type GetAddrListReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	AddrList             []string `protobuf:"bytes,2,rep,name=addr_list,json=addrList,proto3" json:"addr_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddrListReply) Reset()         { *m = GetAddrListReply{} }
func (m *GetAddrListReply) String() string { return proto.CompactTextString(m) }
func (*GetAddrListReply) ProtoMessage()    {}
func (*GetAddrListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{1}
}

func (m *GetAddrListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddrListReply.Unmarshal(m, b)
}
func (m *GetAddrListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddrListReply.Marshal(b, m, deterministic)
}
func (m *GetAddrListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddrListReply.Merge(m, src)
}
func (m *GetAddrListReply) XXX_Size() int {
	return xxx_messageInfo_GetAddrListReply.Size(m)
}
func (m *GetAddrListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddrListReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddrListReply proto.InternalMessageInfo

func (m *GetAddrListReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAddrListReply) GetAddrList() []string {
	if m != nil {
		return m.AddrList
	}
	return nil
}

type GetAddrReq struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddrReq) Reset()         { *m = GetAddrReq{} }
func (m *GetAddrReq) String() string { return proto.CompactTextString(m) }
func (*GetAddrReq) ProtoMessage()    {}
func (*GetAddrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{2}
}

func (m *GetAddrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddrReq.Unmarshal(m, b)
}
func (m *GetAddrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddrReq.Marshal(b, m, deterministic)
}
func (m *GetAddrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddrReq.Merge(m, src)
}
func (m *GetAddrReq) XXX_Size() int {
	return xxx_messageInfo_GetAddrReq.Size(m)
}
func (m *GetAddrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddrReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddrReq proto.InternalMessageInfo

func (m *GetAddrReq) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type GetAddrReply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAddrReply) Reset()         { *m = GetAddrReply{} }
func (m *GetAddrReply) String() string { return proto.CompactTextString(m) }
func (*GetAddrReply) ProtoMessage()    {}
func (*GetAddrReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{3}
}

func (m *GetAddrReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAddrReply.Unmarshal(m, b)
}
func (m *GetAddrReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAddrReply.Marshal(b, m, deterministic)
}
func (m *GetAddrReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAddrReply.Merge(m, src)
}
func (m *GetAddrReply) XXX_Size() int {
	return xxx_messageInfo_GetAddrReply.Size(m)
}
func (m *GetAddrReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAddrReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAddrReply proto.InternalMessageInfo

func (m *GetAddrReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetAddrReply) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAddrListReq)(nil), "route.GetAddrListReq")
	proto.RegisterType((*GetAddrListReply)(nil), "route.GetAddrListReply")
	proto.RegisterType((*GetAddrReq)(nil), "route.GetAddrReq")
	proto.RegisterType((*GetAddrReply)(nil), "route.GetAddrReply")
}

func init() { proto.RegisterFile("route.proto", fileDescriptor_0984d49a362b6b9f) }

var fileDescriptor_0984d49a362b6b9f = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xca, 0x2f, 0x2d,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x8c, 0xb9, 0xf8, 0xdc,
	0x53, 0x4b, 0x1c, 0x53, 0x52, 0x8a, 0x7c, 0x32, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0x14, 0xb9,
	0x78, 0x8a, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0xe3, 0xf3, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15,
	0x18, 0x35, 0x38, 0x83, 0xb8, 0xa1, 0x62, 0x7e, 0x89, 0xb9, 0xa9, 0x4a, 0xce, 0x5c, 0x02, 0x28,
	0x9a, 0x0a, 0x72, 0x2a, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x20, 0xca, 0x59, 0x83, 0xc0,
	0x6c, 0x21, 0x69, 0x2e, 0xce, 0xc4, 0x94, 0x94, 0xa2, 0xf8, 0x9c, 0xcc, 0xe2, 0x12, 0x09, 0x26,
	0x05, 0x66, 0x0d, 0xce, 0x20, 0x8e, 0x44, 0xa8, 0x2e, 0x25, 0x7d, 0x2e, 0x2e, 0xa8, 0x21, 0x44,
	0xda, 0x6a, 0xc6, 0xc5, 0x03, 0xd7, 0x80, 0xcb, 0x46, 0x21, 0x2e, 0x16, 0x90, 0x05, 0x12, 0x4c,
	0x60, 0xed, 0x60, 0xb6, 0x51, 0x0b, 0x23, 0x17, 0x0f, 0xd8, 0xb3, 0xc1, 0x10, 0xc3, 0x84, 0xec,
	0xb9, 0xb8, 0x91, 0x9c, 0x2f, 0x24, 0xaa, 0x07, 0x09, 0x17, 0xd4, 0x70, 0x90, 0x12, 0xc7, 0x26,
	0x5c, 0x90, 0x53, 0xa9, 0xc4, 0x20, 0x64, 0xcc, 0xc5, 0x0e, 0x15, 0x15, 0x12, 0x44, 0x55, 0x05,
	0xd2, 0x28, 0x8c, 0x2e, 0x04, 0xd6, 0x94, 0xc4, 0x06, 0x0e, 0x77, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x62, 0x10, 0x09, 0xa6, 0x86, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteServiceClient is the client API for RouteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteServiceClient interface {
	GetAddrList(ctx context.Context, in *GetAddrListReq, opts ...grpc.CallOption) (*GetAddrListReply, error)
	GetAddr(ctx context.Context, in *GetAddrReq, opts ...grpc.CallOption) (*GetAddrReply, error)
}

type routeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRouteServiceClient(cc *grpc.ClientConn) RouteServiceClient {
	return &routeServiceClient{cc}
}

func (c *routeServiceClient) GetAddrList(ctx context.Context, in *GetAddrListReq, opts ...grpc.CallOption) (*GetAddrListReply, error) {
	out := new(GetAddrListReply)
	err := c.cc.Invoke(ctx, "/route.routeService/GetAddrList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeServiceClient) GetAddr(ctx context.Context, in *GetAddrReq, opts ...grpc.CallOption) (*GetAddrReply, error) {
	out := new(GetAddrReply)
	err := c.cc.Invoke(ctx, "/route.routeService/GetAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouteServiceServer is the server API for RouteService service.
type RouteServiceServer interface {
	GetAddrList(context.Context, *GetAddrListReq) (*GetAddrListReply, error)
	GetAddr(context.Context, *GetAddrReq) (*GetAddrReply, error)
}

// UnimplementedRouteServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRouteServiceServer struct {
}

func (*UnimplementedRouteServiceServer) GetAddrList(ctx context.Context, req *GetAddrListReq) (*GetAddrListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddrList not implemented")
}
func (*UnimplementedRouteServiceServer) GetAddr(ctx context.Context, req *GetAddrReq) (*GetAddrReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddr not implemented")
}

func RegisterRouteServiceServer(s *grpc.Server, srv RouteServiceServer) {
	s.RegisterService(&_RouteService_serviceDesc, srv)
}

func _RouteService_GetAddrList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddrListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetAddrList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.routeService/GetAddrList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetAddrList(ctx, req.(*GetAddrListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouteService_GetAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAddrReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServiceServer).GetAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/route.routeService/GetAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServiceServer).GetAddr(ctx, req.(*GetAddrReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "route.routeService",
	HandlerType: (*RouteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddrList",
			Handler:    _RouteService_GetAddrList_Handler,
		},
		{
			MethodName: "GetAddr",
			Handler:    _RouteService_GetAddr_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "route.proto",
}
