// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

// protoc -I=. --go_out=. message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestType int32

const (
	// 心跳
	RequestType_Pong RequestType = 0
	// 握手
	RequestType_Handshake RequestType = 1
	// 上线
	RequestType_Online RequestType = 2
	// 下线
	RequestType_Offline RequestType = 3
	// 文件传输
	RequestType_File RequestType = 4
	// 群发消息
	RequestType_GroupMessage RequestType = 5
	// 私聊消息
	RequestType_PrivateMessage RequestType = 6
	// 系统广播
	RequestType_SystemBroadcast RequestType = 7
)

var RequestType_name = map[int32]string{
	0: "Pong",
	1: "Handshake",
	2: "Online",
	3: "Offline",
	4: "File",
	5: "GroupMessage",
	6: "PrivateMessage",
	7: "SystemBroadcast",
}

var RequestType_value = map[string]int32{
	"Pong":            0,
	"Handshake":       1,
	"Online":          2,
	"Offline":         3,
	"File":            4,
	"GroupMessage":    5,
	"PrivateMessage":  6,
	"SystemBroadcast": 7,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Message struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cmd                  RequestType `protobuf:"varint,2,opt,name=cmd,proto3,enum=message.RequestType" json:"cmd,omitempty"`
	FormId               int64       `protobuf:"varint,3,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	ToId                 int64       `protobuf:"varint,4,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	CreateTime           int64       `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Body                 []byte      `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Length               int32       `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetCmd() RequestType {
	if m != nil {
		return m.Cmd
	}
	return RequestType_Pong
}

func (m *Message) GetFormId() int64 {
	if m != nil {
		return m.FormId
	}
	return 0
}

func (m *Message) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *Message) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type MessageRequest struct {
	Message              *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

type MessageResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MessageListRequest struct {
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 类型，0全部，1未读，1已读
	Type uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	// 分页相关
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size                 uint32   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageListRequest) Reset()         { *m = MessageListRequest{} }
func (m *MessageListRequest) String() string { return proto.CompactTextString(m) }
func (*MessageListRequest) ProtoMessage()    {}
func (*MessageListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MessageListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageListRequest.Unmarshal(m, b)
}
func (m *MessageListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageListRequest.Marshal(b, m, deterministic)
}
func (m *MessageListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageListRequest.Merge(m, src)
}
func (m *MessageListRequest) XXX_Size() int {
	return xxx_messageInfo_MessageListRequest.Size(m)
}
func (m *MessageListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageListRequest proto.InternalMessageInfo

func (m *MessageListRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageListRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *MessageListRequest) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type MessageListResponse struct {
	Total                uint32     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List                 []*Message `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageListResponse) Reset()         { *m = MessageListResponse{} }
func (m *MessageListResponse) String() string { return proto.CompactTextString(m) }
func (*MessageListResponse) ProtoMessage()    {}
func (*MessageListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MessageListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageListResponse.Unmarshal(m, b)
}
func (m *MessageListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageListResponse.Marshal(b, m, deterministic)
}
func (m *MessageListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageListResponse.Merge(m, src)
}
func (m *MessageListResponse) XXX_Size() int {
	return xxx_messageInfo_MessageListResponse.Size(m)
}
func (m *MessageListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageListResponse proto.InternalMessageInfo

func (m *MessageListResponse) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MessageListResponse) GetList() []*Message {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.RequestType", RequestType_name, RequestType_value)
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*MessageRequest)(nil), "message.MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "message.MessageResponse")
	proto.RegisterType((*MessageListRequest)(nil), "message.MessageListRequest")
	proto.RegisterType((*MessageListResponse)(nil), "message.MessageListResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x14, 0x64, 0xbf, 0xe9, 0x4b, 0x37, 0x5d, 0xbd, 0x54, 0xd4, 0x37, 0x56, 0x11, 0x42, 0x51, 0x0f,
	0x3d, 0x94, 0x2b, 0x12, 0x12, 0x07, 0x20, 0x12, 0xa8, 0xc5, 0xf4, 0x1e, 0xb9, 0xf1, 0x4b, 0x6a,
	0xb1, 0xbb, 0x5e, 0xd6, 0x0e, 0x52, 0x38, 0xf3, 0xb3, 0xf8, 0x71, 0xc8, 0xde, 0x8f, 0x82, 0xd4,
	0xdb, 0xcc, 0xd8, 0x6f, 0xde, 0x78, 0x76, 0x21, 0xaf, 0xc9, 0x18, 0xb1, 0xa7, 0xab, 0xb6, 0xd3,
	0x56, 0x63, 0x36, 0xd0, 0xe5, 0x9f, 0x00, 0xb2, 0x2f, 0x3d, 0xc6, 0x39, 0x84, 0x4a, 0xb2, 0xa0,
	0x0c, 0x56, 0x11, 0x0f, 0x95, 0xc4, 0xd7, 0x10, 0x6d, 0x6b, 0xc9, 0xc2, 0x32, 0x58, 0xcd, 0xaf,
	0xcf, 0xaf, 0x46, 0x07, 0x4e, 0x3f, 0x0e, 0x64, 0xec, 0xdd, 0xb1, 0x25, 0xee, 0x2e, 0xe0, 0x05,
	0x64, 0x3b, 0xdd, 0xd5, 0x1b, 0x25, 0x59, 0xe4, 0x87, 0x53, 0x47, 0xd7, 0x12, 0x17, 0x90, 0x58,
	0xed, 0xe4, 0xd8, 0xcb, 0xb1, 0xd5, 0x6b, 0x89, 0x2f, 0x61, 0xb6, 0xed, 0x48, 0x58, 0xda, 0x58,
	0x55, 0x13, 0x4b, 0xfc, 0x11, 0xf4, 0xd2, 0x9d, 0xaa, 0x09, 0x11, 0xe2, 0x7b, 0x2d, 0x8f, 0x2c,
	0x2d, 0x83, 0xd5, 0x29, 0xf7, 0x18, 0x5f, 0x40, 0x5a, 0x51, 0xb3, 0xb7, 0x0f, 0x2c, 0x2b, 0x83,
	0x55, 0xc2, 0x07, 0xb6, 0x7c, 0x0b, 0xf3, 0x21, 0xfd, 0x90, 0x0a, 0x2f, 0x61, 0x7c, 0x9b, 0x7f,
	0xc9, 0xec, 0xba, 0x98, 0x82, 0x8f, 0x37, 0xa7, 0xc7, 0xbf, 0x83, 0xb3, 0x69, 0xda, 0xb4, 0xba,
	0x31, 0x7e, 0xf9, 0x56, 0xcb, 0x7e, 0x36, 0xe1, 0x1e, 0x23, 0x7b, 0xb4, 0x74, 0x5d, 0x9c, 0x3c,
	0x1a, 0x28, 0xc0, 0xc1, 0xe0, 0xb3, 0x32, 0x76, 0x8c, 0x70, 0x01, 0xd9, 0xc1, 0x50, 0xb7, 0x99,
	0xca, 0x4c, 0x1d, 0x5d, 0x4b, 0x67, 0x6e, 0x8f, 0x6d, 0xef, 0x92, 0x73, 0x8f, 0x9d, 0xd6, 0x3a,
	0xe7, 0xa8, 0xd7, 0x1c, 0x76, 0x9a, 0x51, 0xbf, 0xc8, 0xd7, 0x96, 0x73, 0x8f, 0x97, 0x5f, 0x61,
	0xf1, 0xdf, 0xaa, 0x21, 0xef, 0xb9, 0xab, 0xd8, 0x8a, 0xca, 0x6f, 0xca, 0x79, 0x4f, 0xf0, 0x15,
	0xc4, 0x95, 0x32, 0x96, 0x85, 0x65, 0xf4, 0x64, 0x03, 0xfe, 0xf4, 0xf2, 0x77, 0x00, 0xb3, 0x7f,
	0x3e, 0x26, 0x3e, 0x87, 0xf8, 0x56, 0x37, 0xfb, 0xe2, 0x19, 0xe6, 0x70, 0xf2, 0x49, 0x34, 0xd2,
	0x3c, 0x88, 0xef, 0x54, 0x04, 0x08, 0x90, 0xde, 0x34, 0x95, 0x6a, 0xa8, 0x08, 0x71, 0x06, 0xd9,
	0xcd, 0x6e, 0xe7, 0x49, 0xe4, 0x26, 0x3e, 0xa8, 0x8a, 0x8a, 0x18, 0x0b, 0x38, 0xfd, 0xd8, 0xe9,
	0x43, 0x3b, 0x6c, 0x28, 0x12, 0x44, 0x98, 0xdf, 0x76, 0xea, 0xa7, 0xb0, 0x34, 0x6a, 0x29, 0x2e,
	0xe0, 0xec, 0xdb, 0xd1, 0x58, 0xaa, 0xdf, 0x77, 0x5a, 0xc8, 0xad, 0x30, 0xb6, 0xc8, 0xee, 0x53,
	0xff, 0x4b, 0xbe, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x67, 0x02, 0x50, 0xed, 0xa3, 0x02, 0x00,
	0x00,
}
