// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

// protoc -I=. --go_out=. message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestType int32

const (
	RequestType_Request  RequestType = 0
	RequestType_Response RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "Request",
	1: "Response",
}

var RequestType_value = map[string]int32{
	"Request":  0,
	"Response": 1,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type MessageType int32

const (
	// 心跳
	MessageType_Pong MessageType = 0
	// 握手
	MessageType_Handshake MessageType = 1
	// 上线
	MessageType_Online MessageType = 2
	// 下线
	MessageType_Offline MessageType = 3
	// 文件传输
	MessageType_File MessageType = 4
	// 群发消息
	MessageType_GroupMessage MessageType = 5
	// 私聊消息
	MessageType_PrivateMessage MessageType = 6
	// 系统广播
	MessageType_SystemBroadcast MessageType = 7
)

var MessageType_name = map[int32]string{
	0: "Pong",
	1: "Handshake",
	2: "Online",
	3: "Offline",
	4: "File",
	5: "GroupMessage",
	6: "PrivateMessage",
	7: "SystemBroadcast",
}

var MessageType_value = map[string]int32{
	"Pong":            0,
	"Handshake":       1,
	"Online":          2,
	"Offline":         3,
	"File":            4,
	"GroupMessage":    5,
	"PrivateMessage":  6,
	"SystemBroadcast": 7,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type Message struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FormId               int64    `protobuf:"varint,2,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	ToId                 int64    `protobuf:"varint,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	CreateTime           int64    `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Body                 []byte   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Length               int32    `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetFormId() int64 {
	if m != nil {
		return m.FormId
	}
	return 0
}

func (m *Message) GetToId() int64 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *Message) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type MessageRequest struct {
	Type RequestType `protobuf:"varint,1,opt,name=type,proto3,enum=message.RequestType" json:"type,omitempty"`
	Cmd  MessageType `protobuf:"varint,2,opt,name=cmd,proto3,enum=message.MessageType" json:"cmd,omitempty"`
	// Types that are valid to be assigned to Pack:
	//	*MessageRequest_Message
	//	*MessageRequest_Response
	Pack                 isMessageRequest_Pack `protobuf_oneof:"pack"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_Request
}

func (m *MessageRequest) GetCmd() MessageType {
	if m != nil {
		return m.Cmd
	}
	return MessageType_Pong
}

type isMessageRequest_Pack interface {
	isMessageRequest_Pack()
}

type MessageRequest_Message struct {
	Message *Message `protobuf:"bytes,3,opt,name=message,proto3,oneof"`
}

type MessageRequest_Response struct {
	Response *Reply `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

func (*MessageRequest_Message) isMessageRequest_Pack() {}

func (*MessageRequest_Response) isMessageRequest_Pack() {}

func (m *MessageRequest) GetPack() isMessageRequest_Pack {
	if m != nil {
		return m.Pack
	}
	return nil
}

func (m *MessageRequest) GetMessage() *Message {
	if x, ok := m.GetPack().(*MessageRequest_Message); ok {
		return x.Message
	}
	return nil
}

func (m *MessageRequest) GetResponse() *Reply {
	if x, ok := m.GetPack().(*MessageRequest_Response); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*MessageRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*MessageRequest_Message)(nil),
		(*MessageRequest_Response)(nil),
	}
}

type Reply struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	MsgId                int64    `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FormId               int64    `protobuf:"varint,3,opt,name=form_id,json=formId,proto3" json:"form_id,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Reply) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Reply) GetFormId() int64 {
	if m != nil {
		return m.FormId
	}
	return 0
}

func (m *Reply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("message.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*MessageRequest)(nil), "message.MessageRequest")
	proto.RegisterType((*Reply)(nil), "message.Reply")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcb, 0x6e, 0xdb, 0x30,
	0x10, 0x34, 0xad, 0x97, 0xbb, 0x72, 0x54, 0x62, 0xd3, 0x87, 0x6e, 0x35, 0x7c, 0x28, 0x84, 0x20,
	0xc8, 0xc1, 0xfd, 0x83, 0x1c, 0x5a, 0xfb, 0x50, 0x24, 0x60, 0x73, 0x37, 0x14, 0x71, 0xad, 0x08,
	0xb1, 0x44, 0x55, 0x64, 0x0a, 0xe8, 0xde, 0x4f, 0xe8, 0x37, 0xf5, 0xbb, 0x0a, 0x51, 0x54, 0xe3,
	0xe4, 0xb6, 0x33, 0x3b, 0x5c, 0xcc, 0x0c, 0x08, 0x67, 0x35, 0x69, 0x9d, 0x97, 0x74, 0xd5, 0x76,
	0xca, 0x28, 0x8c, 0x1c, 0x5c, 0xff, 0x61, 0x10, 0x7d, 0x1f, 0x67, 0x4c, 0x60, 0x5e, 0xc9, 0x94,
	0xad, 0x58, 0xe6, 0x89, 0x79, 0x25, 0xf1, 0x23, 0x44, 0x07, 0xd5, 0xd5, 0xfb, 0x4a, 0xa6, 0x73,
	0x4b, 0x86, 0x03, 0xdc, 0x49, 0x3c, 0x87, 0xc0, 0xa8, 0x81, 0xf6, 0x2c, 0xed, 0x1b, 0xb5, 0x93,
	0xf8, 0x09, 0xe2, 0xa2, 0xa3, 0xdc, 0xd0, 0xde, 0x54, 0x35, 0xa5, 0xbe, 0x5d, 0xc1, 0x48, 0xdd,
	0x55, 0x35, 0x21, 0x82, 0x7f, 0xaf, 0x64, 0x9f, 0x06, 0x2b, 0x96, 0x2d, 0x85, 0x9d, 0xf1, 0x03,
	0x84, 0x47, 0x6a, 0x4a, 0xf3, 0x90, 0x86, 0x2b, 0x96, 0x05, 0xc2, 0xa1, 0xf5, 0x5f, 0x06, 0x89,
	0xb3, 0x25, 0xe8, 0xe7, 0x13, 0x69, 0x83, 0x19, 0xf8, 0xa6, 0x6f, 0xc9, 0xfa, 0x4b, 0x36, 0xef,
	0xae, 0xa6, 0x40, 0x6e, 0x7f, 0xd7, 0xb7, 0x24, 0xac, 0x02, 0x3f, 0x83, 0x57, 0xd4, 0xa3, 0xe7,
	0x53, 0xa1, 0xbb, 0x67, 0x85, 0x83, 0x00, 0x2f, 0x61, 0xaa, 0xc1, 0x06, 0x89, 0x37, 0xfc, 0xb5,
	0x76, 0x3b, 0x13, 0x93, 0x04, 0x2f, 0x61, 0xd1, 0x91, 0x6e, 0x55, 0xa3, 0xc7, 0x70, 0xf1, 0x26,
	0x39, 0xf1, 0xd0, 0x1e, 0xfb, 0xed, 0x4c, 0xfc, 0x57, 0x5c, 0x87, 0xe0, 0xb7, 0x79, 0xf1, 0xb8,
	0xde, 0x43, 0x60, 0x97, 0x43, 0xfa, 0x42, 0xc9, 0xd1, 0x7e, 0x20, 0xec, 0x8c, 0xef, 0x21, 0xac,
	0x75, 0xf9, 0xdc, 0x6f, 0x50, 0xeb, 0x72, 0xf7, 0xa2, 0x77, 0xef, 0x45, 0xef, 0x53, 0x83, 0xfe,
	0x73, 0x83, 0x17, 0x19, 0xc4, 0x27, 0x0d, 0x60, 0x0c, 0x91, 0x83, 0x7c, 0x86, 0x4b, 0x58, 0x08,
	0x67, 0x88, 0xb3, 0x8b, 0xdf, 0x0c, 0xe2, 0x93, 0x0e, 0x70, 0x01, 0xfe, 0xad, 0x6a, 0x4a, 0x3e,
	0xc3, 0x33, 0x78, 0xb3, 0xcd, 0x1b, 0xa9, 0x1f, 0xf2, 0x47, 0xe2, 0x0c, 0x01, 0xc2, 0x9b, 0xe6,
	0x58, 0x35, 0xc4, 0xe7, 0xc3, 0xbd, 0x9b, 0xc3, 0xc1, 0x02, 0x6f, 0x78, 0xf1, 0xb5, 0x3a, 0x12,
	0xf7, 0x91, 0xc3, 0xf2, 0x5b, 0xa7, 0x9e, 0x5a, 0x77, 0x8f, 0x07, 0x88, 0x90, 0xdc, 0x76, 0xd5,
	0xaf, 0xdc, 0xd0, 0xc4, 0x85, 0x78, 0x0e, 0x6f, 0x7f, 0xf4, 0xda, 0x50, 0x7d, 0xdd, 0xa9, 0x5c,
	0x16, 0xb9, 0x36, 0x3c, 0xba, 0x0f, 0xed, 0x0f, 0xfc, 0xf2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x72,
	0xd7, 0x31, 0x13, 0x92, 0x02, 0x00, 0x00,
}
